version: '3.0'
name: microservices-2023
services:
  microservices-2023-mongo:
    image: mongo
    container_name: microservices-2023-mongo
    ports:
      - '${MONGO_PORT}:27017'
  microservices-2023-redis:
    image: redis
    container_name: microservices-2023-redis
    ports:
      - '${REDIS_PORT}:6379'
  microservices-2023-jaeger:
    image: jaegertracing/all-in-one
    container_name: microservices-2023-jaeger
    ports:
      - "${JAEGER_PORT_1}:16686"
      - "${JAEGER_PORT_2}:4317"
      - "${JAEGER_PORT_3}:4318"
  microservices-2023-rabbitmq:
    image: rabbitmq:management
    container_name: microservices-2023-rabbitmq
    ports:
      - "${RABBITMQ_PORT_1}:5672"
      - "${RABBITMQ_PORT_2}:15672"
