version: '3.8'
name: node-authentication
services:
  express_mongo:
    image: mongo
    container_name: node-authentication-mongo
    ports:
      - '37017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
